name: CI/CD

on: [push, workflow_dispatch]

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Build
        run: |
          docker build --pull -t kooldev/php:${{ matrix.version }}-nginx-swoole ${{ matrix.version }}-nginx-swoole
          docker build --pull -t kooldev/php:${{ matrix.version }}-nginx-swoole-prod ${{ matrix.version }}-nginx-swoole-prod

      - name: Tests
        run: |
          docker run kooldev/php:${{ matrix.version }}-nginx-swoole php -r "extension_loaded('swoole') or die(1);"
          docker run kooldev/php:${{ matrix.version }}-nginx-swoole-prod php -r "extension_loaded('swoole') or die(1);"

      - name: Login to DockerHub
        uses: docker/login-action@v1.9.0
        if: github.ref == 'refs/heads/main' && github.repository == 'kool-dev/docker-php-swoole'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to DockerHub
        if: github.ref == 'refs/heads/main' && github.repository == 'kool-dev/docker-php-swoole'
        run: |
          docker push kooldev/php:${{ matrix.version }}-nginx-swoole
          docker push kooldev/php:${{ matrix.version }}-nginx-swoole-prod
